const GENERATED_AUTH_CONFIG = {
    ROUTE_PREFIX: 'auth',
    JWT_PRIVATE_KEY_ENV: 'APP_JWT_PRIVATE_KEY',
    JWT_PUBLIC_KEY_ENV: 'APP_JWT_PUBLIC_KEY',
    ACCESS_TTL: '15m',
    REFRESH_TTL: '7d',
    API_VERSION: 'v1',
    DOCS_PATH_PREFIX: '/docs',
    BOOTSTRAP_EMAIL_ENV: 'APP_BOOTSTRAP_ADMIN_EMAIL',
    BOOTSTRAP_PASSWORD_ENV: 'APP_BOOTSTRAP_ADMIN_PASSWORD',
    BOOTSTRAP_DISPLAY_NAME: 'Admin',
} as const;

export { GENERATED_AUTH_CONFIG };
